### ISSUE TITLE
EPIC: Feeder frontend

### ISSUE THREAD

**Issue by cavis** [PRX/feeder.prx.org#497]
Building out the actual UI.  Must finish many/most of the [prerequisites](https://github.com/PRX/feeder.prx.org/issues/496) first.

Also see: the [Figma Prototypes](https://www.figma.com/proto/Yewv83Q8btHcaOBWCtGgKs/PRX-Dovetail-with-Navigation?page-id=80%3A2947&node-id=2833%3A72886&viewport=798%2C-3032%2C0.25&scaling=min-zoom&starting-point-node-id=80%3A3420&hide-ui=1).

```[tasklist]
### General setup:
- [ ] #503
- [ ] #504
- [ ] #505
- [ ] #506
- [ ] #568
- [ ] #551
- [ ] #618
- [x] Figure out timezones and publish-date picker
```

```[tasklist]
### Podcasts:
- [ ] #507
- [ ] #508
- [ ] #509
- [ ] #620
- [ ] #532
- [ ] #439
- [ ] #536
- [ ] #530
- [ ] #531
- [ ] #634
- [ ] https://github.com/PRX/feeder.prx.org/issues/635
- [ ] https://github.com/PRX/feeder.prx.org/issues/655
```

```[tasklist]
### Episodes:
- [ ] #533
- [ ] #534
- [ ] #472
- [ ] #570
- [ ] #633
- [ ] https://github.com/PRX/feeder.prx.org/issues/642
- [ ] https://github.com/PRX/feeder.prx.org/issues/641
- [ ] https://github.com/PRX/feeder.prx.org/issues/640
- [ ] https://github.com/PRX/feeder.prx.org/issues/651
- [ ] https://github.com/PRX/feeder.prx.org/issues/670
```

```[tasklist]
### Feeds:
- [ ] #535
- [ ] https://github.com/PRX/feeder.prx.org/issues/643
- [ ] https://github.com/PRX/feeder.prx.org/issues/644
```

**Comment by cavis** [comment]
Closing this.  Remaining work to move shows over will be captured in #781 .
