### ISSUE TITLE
Audio Segmenter QA

### ISSUE THREAD

**Issue by cavis** [PRX/feeder.prx.org#772]
Need to identify/triage issues with the segmenter (and the media files tab in general).  And document the exact way to reproduce the errors.

- [x] Do flac files playback in browser?  Does that break the segmenter?  What about other weird audio formats?
    - #827 should have fixed flac.  Need to test some other formats.
- [x] Some JS errors on the segmenter.  Changing tabs and coming back doesn't work so good
- [x] Also on segmenter ... popovers throw errors
- [x] Discard button seems to show up sometimes, for like, no reason?
- [ ] ALSO: do some decent QA on publishing/scheduling/unpublishing the Episode.  What happens when the audio is still processing?  When you try to delete from a published episode?  Etc.
- [x] The card for the segmenter is titled "Mark Segments", but it seems like what's actually being marked is ad breaks (that's also what you select in the control above)
    - Fixed by #831
- [x] If you segment a file, and then trash the audio and upload a new file, you get a "Segmentation bad segmentation" error. I think you have to upload it again to clear things out enough for the UI to be happy
    - Fixed by #816
- [x] Changing the numebr of ad breaks while the segmenter is displayed doesn't add additional ad breaks to set in the segmenter
    - Fixed by #831
- [x] Finding myself in situations where the little orange handles on the markers are not clickable/dragable.  Often after a "set to playahead".
- [x] Audio Segments modal has weird overflow issues. Need to adjust modal styles to allow a flexible width, or adjust segment list in modal to be card-like instead of a table.
```[tasklist]
### Tasks
- [ ] https://github.com/PRX/feeder.prx.org/issues/830
```

**Comment by cavis** [comment]
The informational modal still has overflow issues.  But that was mainly a debugging tool for me, so calling this one good.
