### ISSUE TITLE
EPIC: Feeder show migrations

### ISSUE THREAD

**Issue by cavis** [PRX/feeder.prx.org#781]
Triaging and squashing bugs, in order to start transitioning shows to the new UI.

Bugs/issues tracked via [this google sheet](https://docs.google.com/spreadsheets/d/1ZidmwH3JUM4ag2eb1i5YWkbMqx2PsUrSAQ8Te6LdoPM/edit?usp=sharing), and triaged into actionable GH issues.
```[tasklist]
### Tasks
- [ ] https://github.com/PRX/feeder.prx.org/issues/635
- [ ] https://github.com/PRX/feeder.prx.org/issues/767
- [ ] https://github.com/PRX/feeder.prx.org/issues/768
- [ ] https://github.com/PRX/feeder.prx.org/issues/769
- [ ] https://github.com/PRX/feeder.prx.org/issues/770
- [ ] https://github.com/PRX/feeder.prx.org/issues/771
- [ ] https://github.com/PRX/feeder.prx.org/issues/772
- [ ] https://github.com/PRX/feeder.prx.org/issues/773
- [ ] https://github.com/PRX/feeder.prx.org/issues/774
- [ ] https://github.com/PRX/feeder.prx.org/issues/775
- [ ] https://github.com/PRX/feeder.prx.org/issues/776
- [ ] https://github.com/PRX/feeder.prx.org/issues/777
- [ ] https://github.com/PRX/feeder.prx.org/issues/778
- [ ] https://github.com/PRX/feeder.prx.org/issues/779
- [ ] https://github.com/PRX/feeder.prx.org/issues/780
- [ ] https://github.com/PRX/feeder.prx.org/issues/798
- [ ] https://github.com/PRX/feeder.prx.org/issues/799
- [ ] https://github.com/PRX/feeder.prx.org/issues/800
- [ ] https://github.com/PRX/feeder.prx.org/issues/801
- [ ] https://github.com/PRX/feeder.prx.org/issues/802
- [ ] https://github.com/PRX/feeder.prx.org/issues/832
- [ ] https://github.com/PRX/feeder.prx.org/issues/836
- [ ] https://github.com/PRX/feeder.prx.org/issues/837
- [ ] https://github.com/PRX/feeder.prx.org/issues/841
- [ ] https://github.com/PRX/feeder.prx.org/issues/840
```

```[tasklist]
### Chores (ID, Auth changes, etc)
- [ ] https://github.com/PRX/id.prx.org/issues/233
- [ ] https://github.com/PRX/feeder.prx.org/issues/782
- [x] Migrate account_applications to ID plans
- [x] Triage/fix data belonging to individual / non-authorized accounts
- [ ] https://github.com/PRX/feeder.prx.org/issues/825
- [ ] https://github.com/PRX/dovetail-cdn-arranger/issues/25
- [ ] https://github.com/PRX/feeder.prx.org/issues/839
```

**Comment by cavis** [comment]
We're sort of ready to go on these?  Moving remaining lower priority issues out of the epic, and calling this done.
